#!/usr/bin/env bash
# installing nginx 

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'

echo "Helo World!" | sudo tee /var/www/html/index.html

sudo nginx -t
sudo service nginx reload
